// Code generated by mockery v2.40.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/spacelift-io/spacelift-operator/internal/spacelift/models"
	mock "github.com/stretchr/testify/mock"

	v1beta1 "github.com/spacelift-io/spacelift-operator/api/v1beta1"
)

// SpaceRepository is an autogenerated mock type for the SpaceRepository type
type SpaceRepository struct {
	mock.Mock
}

type SpaceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *SpaceRepository) EXPECT() *SpaceRepository_Expecter {
	return &SpaceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *SpaceRepository) Create(_a0 context.Context, _a1 *v1beta1.Space) (*models.Space, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Space
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta1.Space) (*models.Space, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta1.Space) *models.Space); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Space)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta1.Space) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpaceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SpaceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *v1beta1.Space
func (_e *SpaceRepository_Expecter) Create(_a0 interface{}, _a1 interface{}) *SpaceRepository_Create_Call {
	return &SpaceRepository_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *SpaceRepository_Create_Call) Run(run func(_a0 context.Context, _a1 *v1beta1.Space)) *SpaceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1beta1.Space))
	})
	return _c
}

func (_c *SpaceRepository_Create_Call) Return(_a0 *models.Space, _a1 error) *SpaceRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SpaceRepository_Create_Call) RunAndReturn(run func(context.Context, *v1beta1.Space) (*models.Space, error)) *SpaceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *SpaceRepository) Get(_a0 context.Context, _a1 *v1beta1.Space) (*models.Space, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.Space
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta1.Space) (*models.Space, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta1.Space) *models.Space); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Space)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta1.Space) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpaceRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SpaceRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *v1beta1.Space
func (_e *SpaceRepository_Expecter) Get(_a0 interface{}, _a1 interface{}) *SpaceRepository_Get_Call {
	return &SpaceRepository_Get_Call{Call: _e.mock.On("Get", _a0, _a1)}
}

func (_c *SpaceRepository_Get_Call) Run(run func(_a0 context.Context, _a1 *v1beta1.Space)) *SpaceRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1beta1.Space))
	})
	return _c
}

func (_c *SpaceRepository_Get_Call) Return(_a0 *models.Space, _a1 error) *SpaceRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SpaceRepository_Get_Call) RunAndReturn(run func(context.Context, *v1beta1.Space) (*models.Space, error)) *SpaceRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *SpaceRepository) Update(_a0 context.Context, _a1 *v1beta1.Space) (*models.Space, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.Space
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta1.Space) (*models.Space, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1beta1.Space) *models.Space); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Space)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1beta1.Space) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SpaceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type SpaceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *v1beta1.Space
func (_e *SpaceRepository_Expecter) Update(_a0 interface{}, _a1 interface{}) *SpaceRepository_Update_Call {
	return &SpaceRepository_Update_Call{Call: _e.mock.On("Update", _a0, _a1)}
}

func (_c *SpaceRepository_Update_Call) Run(run func(_a0 context.Context, _a1 *v1beta1.Space)) *SpaceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1beta1.Space))
	})
	return _c
}

func (_c *SpaceRepository_Update_Call) Return(_a0 *models.Space, _a1 error) *SpaceRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SpaceRepository_Update_Call) RunAndReturn(run func(context.Context, *v1beta1.Space) (*models.Space, error)) *SpaceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewSpaceRepository creates a new instance of SpaceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSpaceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SpaceRepository {
	mock := &SpaceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
