# permissions for end users to view policies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: policy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: spacelift-operator
    app.kubernetes.io/part-of: spacelift-operator
    app.kubernetes.io/managed-by: kustomize
  name: policy-viewer-role
rules:
- apiGroups:
  - app.spacelift.io
  resources:
  - policies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.spacelift.io
  resources:
  - policies/status
  verbs:
  - get
