# permissions for end users to edit spaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: spacelift-operator
    app.kubernetes.io/managed-by: kustomize
  name: space-editor-role
rules:
- apiGroups:
  - app.spacelift.io
  resources:
  - spaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.spacelift.io
  resources:
  - spaces/status
  verbs:
  - get
