apiVersion: app.spacelift.io/v1beta1
kind: Policy
metadata:
  labels:
    app.kubernetes.io/name: policy
    app.kubernetes.io/instance: policy-sample
    app.kubernetes.io/part-of: spacelift-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: spacelift-operator
  name: policy-sample
spec:
  # TODO(user): Add fields here
