apiVersion: app.spacelift.io/v1beta1
kind: Context
metadata:
  name: context-sample
spec:
  spaceName: space-sample
  attachments:
    - { stackName: stack-sample }
  environment:
    - id: foo
      value: bar
      description: "insecure"
    - id: bar
      valueFromSecret:
        name: secret-sample
        key: test-value
      description: "secure"
  mountedFiles:
    - id: bar
      value: Zm9vCg==
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-sample
data:
  test-value: c2VjcmV0IHN0cmluZwo=
