## Append samples of your project ##
resources:
- _v1beta1_run.yaml
- _v1beta1_stack.yaml
- _v1beta1_space.yaml
- _v1beta1_context.yaml
- _v1beta1_policy.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
